Kiinteistosovellus/Models/OtherSpendingTypes.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kiinteistosovellus.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class OtherSpendingTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OtherSpendingTypes()
        {
            this.OtherSpendings = new HashSet<OtherSpendings>();
        }
    
        public int OtherSpendingTypeId { get; set; }

        [Required(ErrorMessage = "vaaditaan!")]
        public string TypeName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OtherSpendings> OtherSpendings { get; set; }
    }
}

Kiinteistosovellus/Models/OtherSpendings.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kiinteistosovellus.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class OtherSpendings
    {
        public int OtherSpendingsID { get; set; }

        [Required(ErrorMessage = "vaaditaan!")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime DateBegin { get; set; }

        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string Description { get; set; }

        [Required(ErrorMessage = "vaaditaan!")]
        public int OtherSpendingTypeID { get; set; }

        public Nullable<int> ContractorID { get; set; }

        [Required(ErrorMessage = "vaaditaan!")]
        [DataType(DataType.Currency)]
        public decimal Price { get; set; }
        public string ImageUrl { get; set; }
        public virtual Contractors Contractors { get; set; }
        public virtual OtherSpendingTypes OtherSpendingTypes { get; set; }
    }
}

Kiinteistosovellus/Controllers/OtherSpendingsController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Kiinteistosovellus.Models;
using Kiinteistosovellus.ViewModels;
using Microsoft.Ajax.Utilities;
using Newtonsoft.Json;

namespace Kiinteistosovellus.Controllers
{
    public class OtherSpendingsController : BaseController
    {
        private KiinteistoDBEntities db = new KiinteistoDBEntities();

        public List<OtherSpendingTypes> GetTypes()
        {
            if (Session["UserName"] != null)
            {
                List<OtherSpendingTypes> types = db.OtherSpendingTypes.ToList();
                return types;
            }
            else { return null; }
        }

        [HttpGet]
        public JsonResult FetchTypes()
        {
            if (Session["UserName"] != null)
            {
                var data = GetTypes().Select(c => new { Value = c.OtherSpendingTypeId, Text = c.TypeName });
                return Json(data, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return null;
            }
        }

        // GET: OtherSpendings
        public ActionResult Index()
        {
            if (Session["UserName"] != null)
            {
                var otherSpendings = db.OtherSpendings.Include(o => o.Contractors).Include(o => o.OtherSpendingTypes);
                var distinctYearList = db.OtherTypeSpendingsByMonth.DistinctBy(x => x.Vuosi).ToList();
                ViewBag.Vuosi = new SelectList(distinctYearList, "Vuosi", "Vuosi");
                var kulutyypit = db.OtherSpendings.ToList();
                List<string> othTypeArray = new List<string>();
                for (int i = 0; i < kulutyypit.Count; i++)
                {
                    if (!othTypeArray.Contains(kulutyypit[i].OtherSpendingTypes.TypeName.ToString()))
                    {
                        othTypeArray.Add(kulutyypit[i].OtherSpendingTypes.TypeName.ToString());
                    }
                }
                ViewBag.Kulutyypit = othTypeArray;
                return View(otherSpendings.ToList());
            }
            else { return RedirectToAction("Index", "Home"); }
        }

        public PartialViewResult _IndexTable(string alkuPvm, string loppuPvm, string kulutyypit, string columnNumber, string ascOrDesc)
        {
            DateTime dtAlkuPvmTest;
            DateTime dtLoppuPvmTest;

            DateTime? dtAlkuPvm = null;
            DateTime? dtLoppuPvm = null;

            if (DateTime.TryParse(alkuPvm, out dtAlkuPvmTest))
            {
                dtAlkuPvmTest = DateTime.Parse(alkuPvm);
                dtAlkuPvm = dtAlkuPvmTest;
            }

            if (DateTime.TryParse(loppuPvm, out dtLoppuPvmTest))
            {
                dtLoppuPvmTest = DateTime.Parse(loppuPvm);
                dtLoppuPvm = dtLoppuPvmTest;
            }
            var tempIQueryable = from ms in db.OtherSpendings
                                 select ms;
            IQueryable<OtherSpendings> otherSpendings = null;
            //var monthlySpendings = from ms in db.MonthlySpendings
            //                       where (ms.MonthlySpendingID == 1)
            //                       select ms;
            string strKulutyypit = kulutyypit;


            if (strKulutyypit != "")
            {
                var kulutyyppiArray = strKulutyypit.Split('#');
                HashSet<string> strset = new HashSet<string>(kulutyyppiArray);
                otherSpendings = tempIQueryable.Where(ms => strset.Contains(ms.OtherSpendingTypes.TypeName));
            }
            else
            {
                otherSpendings = tempIQueryable;
            }

            string intColumnNumber = columnNumber;

            //var monthlySpendings = from ms in db.MonthlySpendings
            //                       select ms;

            if (dtAlkuPvm != null && dtLoppuPvm != null)
            {
                otherSpendings = otherSpendings.Where(ms => ((ms.DateBegin >= dtAlkuPvm && ms.DateEnd == null) || (ms.DateEnd >= dtAlkuPvm && ms.DateEnd != null)) && ms.DateBegin <= dtLoppuPvm);
            }
            else if (dtAlkuPvm != null && dtLoppuPvm == null)
            {
                otherSpendings = otherSpendings.Where(ms => (ms.DateBegin >= dtAlkuPvm && ms.DateEnd == null) || (ms.DateEnd >= dtAlkuPvm && ms.DateEnd != null));
            }
            else if (dtAlkuPvm == null && dtLoppuPvm != null)
            {
                otherSpendings = otherSpendings.Where(ms => ms.DateBegin <= dtLoppuPvm);
            }


            switch (columnNumber)
            {
                case "0":
                    if (ascOrDesc == "desc")
                    {
                        otherSpendings = otherSpendings.OrderByDescending(ms => ms.DateBegin);
                    }
                    else
                    {
                        otherSpendings = otherSpendings.OrderBy(ms => ms.DateBegin);
                    }
                    break;
                case "1":
                    if (ascOrDesc == "desc")
                    {
                        otherSpendings = otherSpendings.OrderByDescending(ms => ms.DateEnd ?? ms.DateBegin);
                    }
                    else
                    {
                        otherSpendings = otherSpendings.OrderBy(ms => ms.DateEnd ?? ms.DateBegin);
                    }
                    break;
                case "2":
                    if (ascOrDesc == "desc")
                    {
                        otherSpendings = otherSpendings.OrderByDescending(ms => ms.OtherSpendingTypes.TypeName);
                    }
                    else
                    {
                        otherSpendings = otherSpendings.OrderBy(ms => ms.OtherSpendingTypes.TypeName);
                    }
                    break;
                case "3":
                    if (ascOrDesc == "desc")
                    {
                        otherSpendings = otherSpendings.OrderByDescending(ms => ms.Description);
                    }
                    else
                    {
                        otherSpendings = otherSpendings.OrderBy(ms => ms.Description);
                    }
                    break;
                case "4":
                    if (ascOrDesc == "desc")
                    {
                        otherSpendings = otherSpendings.OrderByDescending(ms => ms.Price);
                    }
                    else
                    {
                        otherSpendings = otherSpendings.OrderBy(ms => ms.Price);
                    }
                    break;
                case "5":
                    if (ascOrDesc == "desc")
                    {
                        otherSpendings = otherSpendings.OrderByDescending(ms => ms.Contractors.Name);
                    }
                    else
                    {
                        otherSpendings = otherSpendings.OrderBy(ms => ms.Contractors.Name);
                    }
                    break;
                case "6":
                    if (ascOrDesc == "desc")
                    {
                        otherSpendings = otherSpendings.OrderByDescending(ms => ms.ImageUrl);
                    }
                    else
                    {
                        otherSpendings = otherSpendings.OrderBy(ms => ms.ImageUrl);
                    }
                    break;
                default:
                    otherSpendings = otherSpendings.OrderByDescending(ms => ms.DateBegin);
                    break;
            }
            return PartialView("/Views/OtherSpendings/_IndexTable.cshtml", otherSpendings);
        }

        public ActionResult Chart(int year)
        {
            if (Session["UserName"] != null)
            {
                decimal tammikuu = 0, helmikuu = 0, maaliskuu = 0, huhtikuu = 0, toukokuu = 0, kesäkuu = 0, heinäkuu = 0, elokuu = 0, syyskuu = 0, lokakuu = 0, marraskuu = 0, joulukuu = 0;
                var othSpendData = from sld in db.OtherTypeSpendingsByMonth
                                   where sld.Vuosi == year
                                   select sld;

                foreach (var m in othSpendData)
                {
                    if (m.Vuosi == year)
                    {
                        tammikuu = tammikuu + m.Tammikuu;
                        helmikuu = helmikuu + m.Helmikuu;
                        maaliskuu = maaliskuu + m.Maaliskuu;
                        huhtikuu = huhtikuu + m.Huhtikuu;
                        toukokuu = toukokuu + m.Toukokuu;
                        kesäkuu = kesäkuu + m.Kesäkuu;
                        heinäkuu = heinäkuu + m.Heinäkuu;
                        elokuu = elokuu + m.Elokuu;
                        syyskuu = syyskuu + m.Syyskuu;
                        lokakuu = lokakuu + m.Lokakuu;
                        marraskuu = marraskuu + m.Marraskuu;
                        joulukuu = joulukuu + m.Joulukuu;
                    }
                }
                decimal[] yearValues = new decimal[12];
                yearValues[0] = tammikuu;
                yearValues[1] = helmikuu;
                yearValues[2] = maaliskuu;
                yearValues[3] = huhtikuu;
                yearValues[4] = toukokuu;
                yearValues[5] = kesäkuu;
                yearValues[6] = heinäkuu;
                yearValues[7] = elokuu;
                yearValues[8] = syyskuu;
                yearValues[9] = lokakuu;
                yearValues[10] = marraskuu;
                yearValues[11] = joulukuu;

                ViewBag.Year = JsonConvert.SerializeObject(yearValues);
                ViewBag.ThisYear = year;

                return PartialView();
            }
            else { return null; }
        }

Kiinteistosovellus/Views/OtherSpendings/BarChart.cshtml
<canvas id="myBarChart"></canvas>

<script src="https://cdn.jsdelivr.net/npm/chart.js@4.0.1/dist/chart.umd.js"></script>
<script>
    $(document).ready(function () {
        var xValues = [@Html.Raw(@ViewBag.Category)];
        let yValues = [@ViewBag.Price];
        new Chart("myBarChart", {
            type: "bar",
            data: {
                labels: xValues,
                datasets: [{
                    data: yValues,
                    borderColor: 'rgba(112, 173, 71)',
                    backgroundColor: 'rgba(112, 173, 71, 0.2)',
                    borderWidth: 2,
                    borderRadius: 5,
                    label: " euro",
                    fill: false
                }]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                plugins: {
                    title: {
                        display: true,
                        text: 'Muut kulut kulutustyypeittäin vuoden @ViewBag.ThisYear aikana.'
                    },
                    legend: {
                        display: true,
                        labels: {
                            usePointStyle: true,
                            pointStyle: 'rectRounded',
                            pointStyleWidth: 70
                        }
                    }
                }
            }
        });
    });
</script>

Kiinteistosovellus/Views/OtherSpendings/Chart.cshtml
<canvas id="myChart"></canvas>

<script src="https://cdn.jsdelivr.net/npm/chart.js@4.0.1/dist/chart.umd.js"></script>
<script>
    $(document).ready(function () {
        var xValues = ["Tammikuu", "Helmikuu", "Maaliskuu", "Huhtikuu", "Toukokuu", "Kesäkuu", "Heinäkuu", "Elokuu", "Syyskuu", "Lokakuu", "Marraskuu", "Joulukuu"];
        let yValues = @ViewBag.Year;
        new Chart("myChart", {
            type: "line",
            data: {
                labels: xValues,
                datasets: [{
                    data: yValues,
                    borderColor: 'rgba(112, 173, 71)',
                    backgroundColor: 'rgba(112, 173, 71, 0.2)',
                    borderWidth: 2,
                    borderRadius: 5,
                    label: " euro",
                    fill: false,
                    tension: 0.3
                }]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                plugins: {
                    title: {
                        display: true,
                        text: 'Muut kulut vuoden @ViewBag.ThisYear aikana.'
                    },
                    legend: {
                        display: true,
                        labels: {
                            usePointStyle: true,
                            pointStyle: 'rectRounded',
                            pointStyleWidth: 70,
                        }
                    }
                }
            }
        });
    });
</script>

Kiinteistosovellus/Views/OtherSpendings/Index.cshtml
@model IEnumerable<Kiinteistosovellus.Models.OtherSpendings>

@{
    ViewBag.Title = "Index";
}

<br />
<h2>Muut kulut</h2>
<br />
<div class="row">
    <div class="col-6">
        <div style="height: 338px" id="chartContainer"></div>
    </div>
    <div class="col-6">
        <div id="chartContainerBar" style="height: 338px"></div>
    </div>
</div>
<br />
<div style="margin-left:40%">@Html.DropDownList("Vuosi", (IEnumerable<SelectListItem>)ViewBag.Vuosi, null, new { @class = "form-control form-select" })</div>
<a class="card-link ikonka creNewOtherSpending" title="Uusi Kulutus" role="button"><img src="/Icons/square-add.svg" height="45"></a>

@*Modal Containers*@
<iframe id="otherSpendingCreate" style="display:none;"></iframe>
<iframe id="otherSpendingEdit" style="display:none;"></iframe>
<iframe id="otherSpendingDelete" style="display:none;"></iframe>

@*//Kuvien modaalit*@
<div id="myModals" class="modal">
    <span class="close">&times;</span>
    <img class="modal-content" id="img01">

</div>

<div class="card border-primary" style="margin:10px 0">
    <div class="card-header bg-primary" style="color: white; font-weight: bold;">Suodatus</div>
    <div class="card-body row">
        <div class="col-md-4">
            <label class="form-label">
                Kulutustyyppi
            </label>
            <div class="dropdown form-group" style="width:93%">
                <div class="form-select form-control" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                    <div id="hidingField" style="margin-left:auto; margin-right:auto; color:gray">-- Valitse suodattimet --</div>
                </div>
                <ul style="width:100%" class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                    @{
                        var array = ViewBag.Kulutyypit;
                        foreach (var item in array)
                        {
                            <li style="width:100%"><a class="dropdown-item activate-this clickable-th">@item</a></li>
                        }
                    }
                </ul>
            </div>
        </div>
        <div class="col-md-3">
            <label class="form-label">
                Aloituspvm
            </label>
            <input type="date" id="beginDate" class="form-control" />
        </div>
        <div class="col-md-3" style="margin-left:1%">
            <label class="form-label">
                Päättymispvm
            </label>
            <input type="date" id="endDate" class="form-control" />
        </div>
    </div>
</div>

<table class="table" id="sortableTable">
    <thead style="position: sticky; top: 0;">
        <tr class="card-header bg-primary" style="color:white">
            <th id="0" class="clickable-th">Aloituspvm<img src="~/Icons/sort.svg" class="sort-icon" /></th>
            <th id="1" class="clickable-th">Päättymispvm<img src="~/Icons/sort.svg" class="sort-icon" /></th>
            <th id="2" class="clickable-th">Kulutustyyppi<img src="~/Icons/sort.svg" class="sort-icon" /></th>
            <th style="width:25%" id="3" class="clickable-th">Kuvaus<img src="~/Icons/sort.svg" class="sort-icon" /></th>
            <th id="4" class="clickable-th">Kokonaishinta<img src="~/Icons/sort.svg" class="sort-icon" /></th>
            <th id="5" class="clickable-th">Urakoitsija<img src="~/Icons/sort.svg" class="sort-icon" /></th>
            <th id="6" class="clickable-th">Kuva<img src="~/Icons/sort.svg" class="sort-icon" /></th>
            <th></th>
        </tr>
    </thead>

    <tbody id="createBodyHere">
    </tbody>


</table>

<script type="text/javascript">
    var editNodes = $(".getOtherSpendingId");
    var deleteNodes = $(".delOtherSpendingId");

    $("th").click(function () {
        var passedID = this.id.toString();
        var allHeaders = $("th");

        for (var i = 0; i < allHeaders.length; i++) {
            ////console.log($(this).attr('id'));
            if (i == $(this).attr('id')) {
                continue;
            }
            $(allHeaders[i]).removeClass("desc");
            $(allHeaders[i]).removeClass("asc");
        }
        //console.log($(this).hasClass("asc"));
        if ($(this).hasClass("asc")) {
            $(this).removeClass("asc");
            $(this).addClass("desc");
            filterTableAJAX(passedID, "desc");
        } else {
            filterTableAJAX(passedID, "asc");
            $(this).removeClass("desc");
            $(this).addClass("asc");
        }
    });

    $(".activate-this").click(function () {
        event.stopPropagation();
        if ($(this).hasClass("active")) {
            $(this).removeClass("active");
            $(this).removeClass("chosen");
        } else {
            $(this).addClass("active");
            $(this).addClass("chosen");
        }

        var activateThis = $(".activate-this");
        var activeSelect = [];
        for (var i = 0; i < activateThis.length; i++) {
            if ($(activateThis[i]).hasClass("active")) {
                activeSelect.push(activateThis[i].innerText);
            }
        }
        var spans = $(".spans");
        //Jos ei löydy mitään, tuodaan placeholder div takaisin, muutoin poistetaan se
        if (activeSelect.length == 0) {
            $("#hidingField").removeClass("d-none");
        } else {
            $("#hidingField").addClass("d-none");
        }
        //Poistaa kaikki span-elementit
        for (var i = 0; i < spans.length; i++) {
            spans[i].remove();
        }

        //Lisää kaikki aktiiviset listaelementit span-elementteinä diviin
        for (var i = 0; i < activeSelect.length; i++) {
            $("#dropdownMenuButton1").append('<span class="badge rounded-pill bg-primary bg-opacity-75 spans">' + activeSelect[i] + '</span>');
        }

        filterTableAJAX("", "");
        //filterTable("hidingField", "dropdownMenuButton1", "beginDate", "endDate");
    });

    $("#filterBtn").click(function () {
        filterTableAJAX("", "");
    });

    function filterTableAJAX(columnNumber, ascOrDesc) {
        //console.log(columnNumber, ascOrDesc);
        var dateBegin = $("#beginDate").val();
        var dtDateBegin;
        if (dateBegin != "") {
            dtDateBegin = new Date(dateBegin);
        }
        ////console.log(dateBegin);
        var dateEnd = $("#endDate").val();
        var dtDateEnd;
        if (dateEnd != "") {
            dtDateEnd = new Date(dateEnd);
        }
        ////console.log(dateBegin);

        var stringTypes = "";

        var activeClassCollection = $(".chosen");
        activeClassCollection.each(function (index, node) {
            //console.log(index, $(node).text());
            if (index == 0) {
                stringTypes += $(node).text();
            } else {
                stringTypes += "#" + $(node).text();
            }

        });
        ////console.log(stringTypes);
        var columnNumberData;
        var ascOrDescData;

        if (columnNumber != null) {
            columnNumberData = columnNumber;
        }

        if (ascOrDesc != null) {
            ascOrDescData = ascOrDesc;
        }

        $.post("@Url.Action("_IndexTable","OtherSpendings")", { alkuPvm: dateBegin, loppuPvm: dateEnd, kulutyypit: stringTypes, columnNumber: columnNumberData, ascOrDesc: ascOrDescData } ,function(data){

            $("#createBodyHere").html(data);
            editNodes = $(".getOtherSpendingId");
            deleteNodes = $(".delOtherSpendingId");

            $(deleteNodes).click(function () {
                createDiv("otherSpendingDelete");
                let otherSpendingId2 = $(this).data("otherspendingid2");
                var url = "/otherspendings/_ModalDelete/?id=" + otherSpendingId2;
                var $detailDivDelete = $("#otherSpendingDelete");

                $.get(url, function (data) {
                    $detailDivDelete.replaceWith(data);
                    $('#ModalOtherSpendingDelete').modal('show');
                });
            });

            $(editNodes).click(function () {
                createDiv("otherSpendingEdit");
                let otherSpendingId = $(this).data("otherspendingid");
                var url = "/otherspendings/_ModalEdit/?id=" + otherSpendingId;
                var $detailDivEdit = $("#otherSpendingEdit");

                $.get(url, function (data) {
                    $detailDivEdit.replaceWith(data);
                    $('#ModalotherSpendingEdit').modal('show');
                });
            });


        });
    }

    $("#beginDate").change(function () {
        //console.log("toimii");
        filterTableAJAX("", "");    });

    $("#endDate").change(function () {
        filterTableAJAX("", "");    });


    $(function () {
        $('#homeClicked').removeClass('active');
        $('#spendingsClicked').addClass('active');
        $('#othersClicked').removeClass('active');
    });

        /* Create Modal Window */
    $(function () {
        $(".creNewOtherSpending").click(function () {
            createDiv("otherSpendingCreate");
            var url = "/OtherSpendings/_ModalCreate";
            var $detailDivCreate = $("#otherSpendingCreate");

            $.get(url, function (data) {
                $detailDivCreate.replaceWith(data);
                $('#ModalOtherSpendingCreate').modal('show');
            });
        });
    });

    //On page load showes chart's partials with data for current year
    $(document).ready(async function () {


        var thisYear = new Date().getFullYear();
        document.getElementById("Vuosi").value = thisYear;
        var url = "/OtherSpendings/Chart/?year=" + thisYear;
        var urlBar = "/OtherSpendings/BarChart/?year=" + thisYear;
        var divForPartial = $("#chartContainer");
        var divForPartialBar = $("#chartContainerBar");

        await $.ajax({
            url: url,
            cache: false,
            contentType: false,
            processData: false,
            method: 'get',
            type: "get",
            success: function (result) {
                $(divForPartial).html("");
                $(divForPartial).html(result);
            }
        });
        await $.ajax({
            url: urlBar,
            cache: false,
            contentType: false,
            processData: false,
            method: 'get',
            type: "get",
            success: function (result) {
                $(divForPartialBar).html("");
                $(divForPartialBar).html(result);
            }
        });

        filterTableAJAX("", "");
    });

    //On year's dropdown change showes chart's partials with data for selected year
    $('#Vuosi').change(async function () {
        var thisYear = $(this).val();
        var url = "/OtherSpendings/Chart/?year=" + thisYear;
        var urlBar = "/OtherSpendings/BarChart/?year=" + thisYear;
        var divForPartial = $("#chartContainer");
        var divForPartialBar = $("#chartContainerBar");

            await $.ajax({
                url: url,
                cache: false,
                contentType: false,
                processData: false,
                method: 'get',
                type: "get",
                success: function (result) {
                    $(divForPartial).html("");
                    $(divForPartial).html(result);
                }
            });
            await $.ajax({
                url: urlBar,
                cache: false,
                contentType: false,
                processData: false,
                method: 'get',
                type: "get",
                success: function (result) {
                    $(divForPartialBar).html("");
                    $(divForPartialBar).html(result);
                }
            });
        });

</script>

Kiinteistosovellus/Views/OtherSpendings/_IndexTable.cshtml
@model IEnumerable<Kiinteistosovellus.Models.OtherSpendings>

@foreach (var item in Model)
{
    <tr class="card-body filtering">
        <td>@Html.ValueFor(modelItem => item.DateBegin, "{0:dd.MM.yyyy}")</td>
        @{
            if (item.DateEnd != null)
            {
                <td>@Html.ValueFor(modelItem => item.DateEnd, "{0:dd.MM.yyyy}")</td>
            }
            else
            {
                <td>@Html.ValueFor(modelItem => item.DateBegin, "{0:dd.MM.yyyy}")</td>
            }
        }
        <td>@Html.DisplayFor(modelItem => item.OtherSpendingTypes.TypeName)</td>
        <td style="word-break:break-word;  width:25%;">@Html.DisplayFor(modelItem => item.Description)</td>
        <td>@Html.DisplayFor(modelItem => item.Price)</td>
        <td>@Html.DisplayFor(modelItem => item.Contractors.Name)</td>
        <td>
            @if (item.ImageUrl != null)
            {
                <img class="images" src="@Html.DisplayFor(modelItem => item.ImageUrl)" width="100" />
            }
            else
            {@Html.DisplayFor(modelItem => item.ImageUrl)}
        </td>
        <td>
            <a class="card-link ikonka getOtherSpendingId" title="Muokkaa Kulu" data-otherspendingid="@item.OtherSpendingsID" role="button"><img src="/Icons/square-edit.svg" height="30"></a>
            <a class="card-link ikonka delOtherSpendingId" title="Poista Kulu" data-otherspendingid2="@item.OtherSpendingsID" role="button"><img src="/Icons/square-delete.svg" height="30"></a>
        </td>
    </tr>
}
<script type="text/javascript">

    // create references to the modal...
    var modal = document.getElementById('myModals');
    // to all images -- note I'm using a class!
    var images = document.getElementsByClassName('images');
    // the image in the modal
    var modalImg = document.getElementById("img01");
    // and the caption in the modal
    // var captionText = document.getElementById("caption");

    // Go through all of the images with our custom class
    for (var i = 0; i < images.length; i++) {
        var img = images[i];
        // and attach our click listener for this image.
        img.onclick = function (evt) {
            modal.style.display = "block";
            modalImg.src = this.src;
            //captionText.innerHTML = this.alt;
        }
    }

    var span = document.getElementsByClassName("close")[0];

    span.onclick = function () {
        modal.style.display = "none";
    }
</script>